db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=asdfasdf

mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080

web:
  build: .
  command: rails server -b 0.0.0.0
  ports:
    - '3000:3000'
  volumes:
    - '.:/usr/src/app'
  links:
    - db
    - mailcatcher
