# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00875b53748d2f176607c762ee4b100dc5030376ba788b74b023d5371cf3068a13694ced2d2aa98067eb816710b314752d3ece6d4dd473847d9fb32bd9272f22

test:
  secret_key_base: f69049a55eb27740995f47501be3e8ab215e0531d213cfae994fa850fe568a424e5f2577814a5b4f0211a8b309c9b39a3bff372e307612ce22d0fd95e4e1d660

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
